export const campaign = {
  id: 'current',
  title: 'Base Mission Farm',
  description: 'Destinação dos recursos da Base Missionária.',
  active: true,
  version: 4,
  totalGoalCents: 4000000,
  totalRaisedCents: 3500000,
  percent: 87.5,
  goalExceeded: false,
  updatedAt: '2026-09-20T12:00:00Z',
  stages: [
    {
      id: 'aquisicao',
      name: 'Aquisição',
      description: 'Garantir o lugar para as próximas gerações.',
      goalCents: 2000000,
      raisedCents: 3000000,
      percent: 150,
      remainingCents: 0,
      goalExceeded: true,
      status: 'EM_ANDAMENTO',
      icon: 'key',
      sortOrder: 1,
      current: true,
      visible: true,
      updatedAt: '2026-09-20T12:00:00Z',
      updatedBy: 'admin-test',
    },
    {
      id: 'revitalizacao',
      name: 'Revitalização',
      description: 'Transformar estruturas em vidas.',
      goalCents: 2000000,
      raisedCents: 500000,
      percent: 25,
      remainingCents: 1500000,
      goalExceeded: false,
      status: 'EM_BREVE',
      icon: 'tool',
      sortOrder: 2,
      current: false,
      visible: true,
      updatedAt: '2026-09-20T12:00:00Z',
      updatedBy: 'admin-test',
    },
  ],
};

export const checkoutUrls = [
  'https://www.asaas.com/c/hqo6c6vj1umdq9do',
  'https://www.asaas.com/c/t2wa3p32k2icavu5',
  'https://www.asaas.com/c/7ej20acvct9oftvd',
  'https://www.asaas.com/c/rcw3n6od2iagsue7',
  'https://www.asaas.com/c/p4t4yq4wup3f5uc4',
  'https://www.asaas.com/c/v4c8p88ew5yktmmf',
];
